### ISSUE TITLE
please check Adapter with js-controller 3.x

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.upnp#47]
`

host.ioB-D10 | 2020-04-13 11:34:06.032 | info | "system.adapter.upnp.0" disabled
-- | -- | -- | --
upnp.0 | 2020-04-13 11:33:53.367 | warn | (9502) This value will not be set in future versions. Please report this to the developer.
upnp.0 | 2020-04-13 11:33:53.366 | warn | (9502) State value to set is invalid for  upnp.0.WANConnectionDevice.WANDevice.WANConnectionDevice.Alive: The  state property "expire" has the wrong type "string" (should be  "number")!
upnp.0 | 2020-04-13 11:33:35.665 | warn | (9502) This object will not be created in future versions. Please report this to the developer.
upnp.0 | 2020-04-13 11:33:35.664 | warn | (9502) Object upnp.0.LichtKueche.controllee.basicevent.BinaryState is  invalid: obj.common.type has an invalid value (bool) but has to be one  of number, string, boolean, array, object, mixed, file, js
upnp.0 | 2020-04-13 11:33:17.393 | warn | (9502) adapter.objects.getObjectView is deprecated, and will be removed  in the future. Please use adapter.getObjectView/Async. Report this to  Developer!
host.ioB-D10 | 2020-04-13 11:33:16.188 | info | instance system.adapter.upnp.0 started with pid 9502
host.ioB-D10 | 2020-04-13 11:33:16.177 | info | "system.adapter.upnp.0" enabled

`

**Comment by FRYYYYYY** [comment]
Yes, same here since the upgrade of the js controller

**Comment by Jey-Cee** [comment]
Test from Github, version is 1.0.15
