### ISSUE TITLE
Update von js-controller BETA 3.2.2 

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.upnp#63]
Hallo, nach einen Update auf JSC BETA 3.2.2 kommt folgendes:

`

upnp.0 | 2021-01-09 10:09:16.550 | warn | (14192) State "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.X_AVM_DE_GetIPTVInfos.sid" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
upnp.0 | 2021-01-09 10:09:16.550 | warn | (14192) State "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.GetAddonInfos.sid" has no existing object, this might lead to an error in future versions
upnp.0 | 2021-01-09 10:09:16.550 | warn | (14192) State "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.GetCommonLinkProperties.sid" has no existing object, this might lead to an error in future versions
upnp.0 | 2021-01-09 10:09:16.550 | warn | (14192) State "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.GetTotalBytesReceived.sid" has no existing object, this might lead to an error in future versions
upnp.0 | 2021-01-09 10:09:16.550 | warn | (14192) State "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.GetTotalPacketsReceived.sid" has no existing object, this might lead to an error in future versions
upnp.0 | 2021-01-09 10:09:16.550 | warn | (14192) State "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.GetTotalBytesSent.sid" has no existing object, this might lead to an error in future versions
upnp.0 | 2021-01-09 10:09:16.549 | warn | (14192) State "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.GetTotalPacketsSent.sid" has no existing object, this might lead to an error in future versions
upnp.0 | 2021-01-09 10:09:16.549 | warn | (14192) State "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.X_AVM_DE_GetDsliteStatus.sid" has no existing object, this might lead to an error in future versions

`

**Comment by Mercator18** [comment]
Auch ich hatte im Log sehr viele ähnliche Einträge für verschiedenste gefundene Geräte. 
Ich habe den fehlenden "sid" DP bei einigen manuell eingetragen, woraufhin dann erwartungsgemäß keine Einträge im LOG mehr vorkamen. Sind mir aber dann doch zu viele Einträge, um das manuell zu machen.
Allerdings läuft mein Log aktuell mit if valueSID Einträgen voll.

**Comment by MarkSau** [comment]
Da schließe ich mich an. Auch ich habe da so einige dieser Meldungen im Log.
`

upnp.0 | 2021-02-04 11:11:23.712 | warn | (1321) State "upnp.0.WANDevice_-_FRITZ!Box_7590.WANDevice.WANCommonInterfaceConfig.GetAddonInfos.sid" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
upnp.0 | 2021-02-04 11:11:23.712 | warn | (1321) State "upnp.0.WANDevice_-_FRITZ!Box_7590.WANDevice.WANCommonInterfaceConfig.GetCommonLinkProperties.sid" has no existing object, this might lead to an error in future versions
upnp.0 | 2021-02-04 11:11:23.708 | warn | (1321) State "upnp.0.WANDevice_-_FRITZ!Box_7590.WANDevice.WANCommonInterfaceConfig.GetTotalBytesReceived.sid" has no existing object, this might lead to an error in future versions
upnp.0 | 2021-02-04 11:11:23.707 | warn | (1321) State "upnp.0.WANDevice_-_FRITZ!Box_7590.WANDevice.WANCommonInterfaceConfig.GetTotalBytesSent.sid" has no existing object, this might lead to an error in future versions
upnp.0 | 2021-02-04 11:11:23.706 | warn | (1321) State "upnp.0.WANDevice_-_FRITZ!Box_7590.WANDevice.WANCommonInterfaceConfig.X_AVM_DE_GetIPTVInfos.sid" has no existing object, this might lead to an error in future versions
upnp.0 | 2021-02-04 11:11:23.688 | warn | (1321) State "upnp.0.WANDevice_-_FRITZ!Box_7590.WANDevice.WANCommonInterfaceConfig.GetTotalPacketsReceived.sid" has no existing object, this might lead to an error in future versions
upnp.0 | 2021-02-04 11:11:23.687 | warn | (1321) State "upnp.0.WANDevice_-_FRITZ!Box_7590.WANDevice.WANCommonInterfaceConfig.GetTotalPacketsSent.sid" has no existing object, this might lead to an error in future versions
upnp.0 | 2021-02-04 11:11:23.678 | warn | (1321) State "upnp.0.WANDevice_-_FRITZ!Box_7590.WANDevice.WANCommonInterfaceConfig.X_AVM_DE_GetDsliteStatus.sid" has no existing object, this might lead to an error in future versions

`

**Comment by Boronsbruder** [comment]
Auch mit dem Stable des Js-controller 3.2.16 sind einige Warnungen
[Log auf Pastebin](https://pastebin.com/BupXQJLJ)

**Comment by Jey-Cee** [comment]
Ist mit 1.0.17 gefixt
