### ISSUE TITLE
Update js-controller 3.3.1 Warn Meldungen

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.upnp#71]
Hallo,

nach einen Update des js-controllers auf V 3.3.1 kommen folgende Warnmeldungen:

`

upnp.0 | 2021-04-30 06:35:00.364 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.ByteSendRate" has wrong type "string" but has to be "number"
-- | -- | -- | --
upnp.0 | 2021-04-30 06:35:00.348 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.ByteReceiveRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:35:00.333 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.PacketSendRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:35:00.316 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.PacketReceiveRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:35:00.300 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.TotalBytesSent" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:35:00.284 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.TotalBytesReceived" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:35:00.268 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.AutoDisconnectTime" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:35:00.253 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.IdleDisconnectTime" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:35:00.173 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.UpnpControlEnabled" has wrong type "string" but has to be "boolean"
upnp.0 | 2021-04-30 06:35:00.157 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.RoutedBridgedModeBoth" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:34:00.356 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.ByteSendRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:34:00.339 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.ByteReceiveRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:34:00.322 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.PacketSendRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:34:00.308 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.PacketReceiveRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:34:00.292 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.TotalBytesSent" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:34:00.277 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.TotalBytesReceived" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:34:00.259 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.AutoDisconnectTime" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:34:00.244 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.IdleDisconnectTime" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:34:00.164 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.UpnpControlEnabled" has wrong type "string" but has to be "boolean"
upnp.0 | 2021-04-30 06:34:00.148 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.RoutedBridgedModeBoth" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:33:00.351 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.ByteSendRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:33:00.336 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.ByteReceiveRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:33:00.319 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.PacketSendRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:33:00.304 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.PacketReceiveRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:33:00.289 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.TotalBytesSent" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:33:00.277 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.TotalBytesReceived" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:33:00.273 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.AutoDisconnectTime" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:33:00.256 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.IdleDisconnectTime" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:33:00.177 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.UpnpControlEnabled" has wrong type "string" but has to be "boolean"
upnp.0 | 2021-04-30 06:33:00.159 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.RoutedBridgedModeBoth" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:32:00.342 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.ByteSendRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:32:00.326 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.ByteReceiveRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:32:00.312 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.PacketSendRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:32:00.296 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.PacketReceiveRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:32:00.276 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.TotalBytesSent" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:32:00.261 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.TotalBytesReceived" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:32:00.245 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.AutoDisconnectTime" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:32:00.230 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.IdleDisconnectTime" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:32:00.151 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.UpnpControlEnabled" has wrong type "string" but has to be "boolean"
upnp.0 | 2021-04-30 06:32:00.134 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.RoutedBridgedModeBoth" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:31:00.373 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.ByteSendRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:31:00.359 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.ByteReceiveRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:31:00.343 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.PacketSendRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:31:00.326 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.PacketReceiveRate" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:31:00.311 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.TotalBytesSent" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:31:00.296 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.TotalBytesReceived" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:31:00.280 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.AutoDisconnectTime" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:31:00.264 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.IdleDisconnectTime" has wrong type "string" but has to be "number"
upnp.0 | 2021-04-30 06:31:00.185 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.UpnpControlEnabled" has wrong type "string" but has to be "boolean"
upnp.0 | 2021-04-30 06:31:00.169 | warn | (10372) State value to set for "upnp.0.WANDevice_-_FRITZ!Box_6590_Cable.WANDevice.WANCommonInterfaceConfig.RoutedBridgedModeBoth" has wrong type "string" but has to be "number"

`

**Comment by BassT23** [comment]
Weitere Fehler:

![Screenshot_20210604-185756_Chrome](https://user-images.githubusercontent.com/30832786/120837349-df61d980-c566-11eb-8b16-9d9b7d509ee9.jpg)

Vorläufiger fix: umstellen auf "warnung"

**Comment by Jey-Cee** [comment]
@BassT23 lösch mal alle Objekte und starte denn Adapter neu. Sieht aus als wenn du noch ein Problem aus einer deutlich älteren Version mit schleppst.

**Comment by Starcon79** [comment]
Leider kommen immer noch Warnmeldungen im Log trotz löschen der Datenpunkte. Die Meldungen kommen immer wenn der "request" Button betätigt wird.

![screenshot-192 168 178 46_8081-2021 08 25-12_38_22](https://user-images.githubusercontent.com/38224290/130784354-7081a086-a2a7-4803-9ec2-42e4a52c7cbc.png)
