### ISSUE TITLE
Fehler jsonConfig

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.upnp#83]
Hallo, Fehler jsonConfig  kommt noch immer.

![Screenshot (3926)](https://user-images.githubusercontent.com/41079106/124449747-0b4dc600-dd84-11eb-9bdb-2f37032cba07.png)

`Plattform: Windows
RAM: 16 GB 
Node.js: 12.22.1
NPM: 6.14.12
JS Controller: 3.3.14
Admin: 5.1.9
Web: 3.4.3
Socket.io: 3.1.4
Script Engine: 5.2.0`

**Comment by Jey-Cee** [comment]
Ist der Fehler auch mit dem aktuellen js-controller noch vorhanden?

**Comment by sigi2345** [comment]
> Ist der Fehler auch mit dem aktuellen js-controller noch vorhanden?

Ja

`Plattform: Windows
RAM: 16 GB 
Node.js: 12.22.4
NPM: 6.14.14
JS Controller: 3.3.15
Admin: 5.1.18
Web: 3.4.7
Socket.io: 3.1.4
Script Engine: 5.2.8
IOT: 1.8.22
VIS: 1.4.2
HM-Rega: 3.0.29
HM-RPC: 1.14.43
Jarvis: 3.0.0
Backitup: 2.1.12
Cloud: 4.1.0
ICal: 1.11.1
iQontrol: 1.8.1
fb-checkpresence: 1.1.5
Hue: 3.5.19
Alexa2: 3.9.3
Material UI: 1.0.4
E-Charts: 1.0.2
Info: 1.9.7
UPnP: 1:0:19`

**Comment by sigi2345** [comment]
Fehler weg.
